/* Czech prefix data — work in progress.

   One card per root:  [title, base, entries]
     title   the heading; forms are separated by → or /
     base    upper-case forms first (e.g. the iterative), then English meanings
     entries [slot, glosses, example, searchWords]
       slot        a slot on the diagram, optionally with the label to print:
                   'ROZ:ROZE' puts the label ROZE in the ROZ slot
       glosses     meanings separated by ' | '
       example     optional 'Czech sentence. = English sentence.' — belongs to the first gloss
       searchWords optional extra forms for the search box, separated by spaces,
                   for words the prefix + stem rule would miss (sníst, zůstat…)
*/
const RAW = [

['DĚLAT → -DĚLAT', ['DĚLÁVAT','do','make','work'], [
  ['VY', 'earn | make (by working)', 'Vydělal si na auto. = He earned enough for a car.'],
  ['NA', 'make a lot of | run up (debts)'],
  ['OB', 'cultivate (land) | (colloq.) swindle'],
  ['PŘE', 'redo | remake | alter', 'Předělali kuchyň. = They redid the kitchen.'],
  ['PRO', 'lose (money) | undergo (illness)'],
  ['DO', 'finish (making) | complete'],
  ['PŘI', 'attach | fasten | add more'],
  ['ROZ', 'undo | unfasten | light (a fire) | mix (mortar)'],
  ['U', 'do | make (perfective)', 'Udělal chybu. = He made a mistake.'],
  ['ZA', 'knead (dough) | (si) bring trouble on oneself'],
  ['OD', 'remove | take off | (slang) bump off'],
  ['PO', '(vulg.) botch | (se) wet oneself'],
]],

['PRACOVAT → -PRACOVAT', ['PRACOVÁVAT','work'], [
  ['VY', 'work out | draw up | (se) work one’s way up', 'Vypracoval podrobný plán. = He drew up a detailed plan.'],
  ['Z', 'process | handle | work up', 'Zpracoval data. = He processed the data.'],
  ['DO', '(se) arrive at (by work) | finish the work'],
  ['PRO', 'work out in detail | (se) work through'],
  ['PŘE', 'rework | revise | (se) overwork'],
  ['ZA', 'incorporate | train in | (colloq.) get to work'],
  ['OD', 'work (hours) | work off (a debt)'],
  ['NA', '(se) work hard | toil'],
  ['ROZ', 'start work on | leave in progress'],
]],

['ČÍST → -ČÍST', ['ČÍTÁVAT','read'], [
  ['VY', 'read (from) | glean | (vyčítat) reproach'],
  ['NA', 'load | read in (data) | read widely'],
  ['DO', 'finish reading | read to the end', 'Dočetl knihu. = He finished the book.'],
  ['ROZ:ROZE', 'start reading'],
  ['PŘED', 'read aloud (předčítat)'],
  ['ZA', '(se) become absorbed in reading'],
  ['OD:ODE', 'subtract | deduct | read off (a meter)', 'Odečti pět od deseti. = Subtract five from ten.'],
  ['PŘI', 'add | attribute | ascribe'],
  ['PŘE', 'read (through)', 'Přečetl dopis. = He read the letter.'],
  ['PRO', 'read through | peruse'],
  ['PO', '(si) read for a while | (počítat) count'],
  ['S:SE', 'add up | total'],
]],

['JÍST → -JÍST', ['JÍDÁVAT','eat'], [
  ['VY', 'eat up (all) | clean out (the fridge)'],
  ['NA', '(se) eat one’s fill | (se) have a meal', 'Najedl se a usnul. = He ate his fill and fell asleep.'],
  ['DO', 'finish eating'],
  ['PŘE', '(se) overeat'],
  ['PRO', 'spend on food'],
  ['ZA', 'eat sth after (to take the taste away)'],
  ['U', 'eat a bit (off/of)'],
  ['ROZ:ROZE', 'start eating (and leave)'],
  ['S', 'eat up | “polish off”', 'Snědl celou pizzu. = He ate the whole pizza.', 'SNÍST'],
]],

['JÍT: CHODIT → -JÍT', ['CHODÍVAT','go','walk'], [
  ['VY', 'go out | come out | be published | get by (with)', 'Vyšel z domu. = He came out of the house.'],
  ['OB:OBE', 'walk around | bypass | (se bez) do without', 'Obešel dům. = He walked around the house.'],
  ['NA', 'find', 'Našel klíče. = He found his keys.', 'NAJÍT'],
  ['VZ:VZE', 'arise | emerge (from)', 'Z diskuse vzešel nový plán. = A new plan emerged from the discussion.'],
  ['ROZ:ROZE', '(se) split up | (se) part', 'Rozešli se po deseti letech. = They split up after ten years.'],
  ['PŘE', 'cross | go over | pass (pain) | switch to', 'Přešel ulici. = He crossed the street.'],
  ['PRO', 'go through | pass (exam) | (se) take a walk', 'Prošel zkouškou. = He passed the exam.'],
  ['PŘI', 'come | arrive | (o) lose | (na) figure out', 'Přišel pozdě. = He came late.'],
  ['U', 'walk (a distance) | escape (notice) | (ujde to) be OK', 'Ušli dvacet kilometrů. = They walked twenty kilometres.'],
  ['ZA', 'drop in | go too far | set (sun)', 'Zajdeme na pivo? = Shall we go for a beer?'],
  ['PŘED:PŘEDE', 'prevent | forestall | go ahead of', 'Nehodě se dalo předejít. = The accident could have been prevented.'],
  ['OD:ODE', 'leave | depart', 'Odešel bez rozloučení. = He left without saying goodbye.'],
  ['V:VE', 'enter | go in | (se) fit', 'Vešel do pokoje. = He went into the room.'],
  ['PO', 'die (of animals) | perish'],
  ['S:SE', 'go down | (se) meet | (z cesty) stray', 'Sejdeme se v šest. = Let’s meet at six.'],
  ['POD:PODE', 'go under | pass beneath'],
  ['DO', 'reach | get to | run out | dawn on (sb)', 'Došli jsme až k lesu. = We walked as far as the forest.'],
  ['NAD:NADE', 'come (of time) | arrive', 'Nadešel čas odchodu. = The time to leave had come.'],
]],

['-CHÁZET', ['(imperfective)','go','walk'], [
  ['VY', 'come out | get along (with) | proceed from'],
  ['NAD', 'be coming up (nadcházející = upcoming)'],
  ['OB', 'walk around | bypass | do the rounds'],
  ['VZ', 'arise | emerge | sprout'],
  ['NA', 'find | (se) be situated'],
  ['DO', 'commute | attend | run out | occur'],
  ['ROZ', '(se) part | (se) diverge'],
  ['PŘE', 'cross | pass | pace (up and down)'],
  ['PRO', 'go through | (se) stroll'],
  ['U', '(se o) apply for | court | leak (gas)'],
  ['PŘED', 'precede | prevent | forestall'],
  ['ZA', '(s) handle | treat | go too far | set'],
  ['OD', 'leave | depart | be passing'],
  ['PŘI', 'be coming | arrive'],
  ['S', 'go down | (se) meet | be missing (schází mi)'],
  ['V', 'enter | go in'],
  ['PO', 'come from | originate'],
  ['POD', 'pass under'],
]],

['PSÁT → -PSAT', ['PSÁVAT','write'], [
  ['VY', 'write out | list | announce (a contest)', 'Vypsal si slovíčka. = He wrote out the vocabulary.'],
  ['NAD:NADE', 'address (an envelope) | title | head', 'Nadepsal obálku. = He addressed the envelope.'],
  ['O', 'copy (out) | crib | paraphrase | circumscribe', 'Opsal úkol od spolužáka. = He copied the homework from a classmate.'],
  ['NA', 'write (perfective) | compose', 'Napsal dopis. = He wrote a letter.'],
  ['ROZ:ROZE', 'break down | itemize | start writing', 'Rozepsal náklady. = He broke down the costs.'],
  ['PŘI', 'add in writing | credit (to account) | ascribe', 'Připsal poznámku. = He added a note.'],
  ['PŘED:PŘEDE', 'prescribe | stipulate', 'Lékař mi předepsal antibiotika. = The doctor prescribed me antibiotics.'],
  ['U', '(se) sign oneself over | subscribe (shares)', 'Upsal se ďáblu. = He sold his soul to the devil.'],
  ['DO', 'finish writing', 'Dopsal knihu. = He finished writing the book.'],
  ['PŘE', 'rewrite | transcribe | overwrite | transfer', 'Přepsal text. = He rewrote the text.'],
  ['PRO', 'show through (ink)', 'Inkoust se propsal na druhou stranu. = The ink showed through to the other side.'],
  ['ZA', 'write down | record | enrol', 'Zapsal si číslo. = He wrote down the number.'],
  ['OD:ODE', 'write back | reply | write off', 'Odepsal mi hned. = He wrote back to me straight away.'],
  ['V:VE', 'inscribe | write in', 'Vepsal jméno do knihy. = He wrote his name in the book.'],
  ['PO', 'describe | cover with writing', 'Popsal, co viděl. = He described what he saw.'],
  ['S:SE', 'draw up | write up | compile', 'Sepsali smlouvu. = They drew up a contract.'],
  ['POD:PODE', 'sign', 'Podepsal smlouvu. = He signed the contract.'],
]],

['HODIT → -HODIT', ['throw','fling','toss'], [
  ['NAD', 'toss up | bring up (a topic) | raise'],
  ['VY', 'throw out/away | fire (from a job) | blow up'],
  ['NA', 'throw on | start (engine) | roughcast | hint'],
  ['PŘI', 'throw in | add | raise (a bid) | (se) happen'],
  ['ROZ', 'scatter | throw off balance | upset'],
  ['PŘE', 'throw over | swap | switch (gear, lever)'],
  ['PŘED', 'throw before sb | put before'],
  ['ZA', 'throw away | waste | squander'],
  ['OD', 'throw off | discard | cast aside'],
  ['DO', 'throw as far as | arrange (for sb)'],
  ['PO', 'toss (carelessly) | leave lying about'],
  ['V', 'throw in | drop in (a letter)'],
  ['S', 'throw down | knock down | lose weight | belittle'],
  ['POD', 'slip under | foist'],
  ['U', 'hit | strike | (frost) set in'],
]],

['LEŽET → -LOŽIT', ['LEŽÍVAT','lie / lay'], [
  ['VY', 'unload | lay out | explain | interpret'],
  ['OB', 'line | panel | tile | garnish'],
  ['NA', 'load | pickle | (s) deal with'],
  ['PŘI', 'attach | enclose | put on (fire) | apply'],
  ['ROZ', 'spread out | take apart | decompose'],
  ['PŘED', 'present | submit | put forward'],
  ['U', 'put away | store | save (a file) | impose'],
  ['PŘE', 'translate | relocate | transfer | fold over'],
  ['PRO', 'interleave | intersperse'],
  ['ZA', 'found | establish | file | mislay | pawn'],
  ['OD', 'postpone | put aside | take off (coat)'],
  ['DO', 'document | prove | support with evidence'],
  ['V', 'insert | deposit | paste'],
  ['PO', 'put | lay down | ask (a question) | hang up'],
  ['S', 'fold | compose | pass (an exam) | lay down'],
  ['POD', 'underlay | support | back up'],
]],

['DÁT → -DAT', ['DÁVAT','give'], [
  ['VY', 'publish | issue | give out | (se) set out'],
  ['VZ', 'give up | surrender | (hold) pay tribute'],
  ['NA', '(se) expect | nadaný = gifted'],
  ['ROZ', 'give away | distribute | deal (cards)'],
  ['PŘI', 'add | speed up | (se) join | take sides'],
  ['PRO', 'sell'],
  ['PŘED', 'hand over | pass on'],
  ['DO', 'deliver | supply | add (in speech)'],
  ['U', 'denounce | state (a reason) | (se) happen'],
  ['ZA', 'assign | enter (data) | commission | (si) compromise oneself'],
  ['OD', '(se) devote oneself | marry (a couple) | (odevzdat) hand in'],
  ['PO', 'hand | pass | serve | file | administer'],
  ['V', '(se) marry (of a woman)'],
  ['Z', '(se) seem | dream'],
  ['POD', '(se) submit | yield | give in'],
]],

['BRÁT → -BRAT', ['BRÁVAT','take'], [
  ['VY', 'choose | pick | collect | withdraw (money)', 'Vybral si modré tričko. = He picked the blue T-shirt.'],
  ['O', 'rob | strip | pick clean'],
  ['NA', 'scoop up | take in | gather (speed) | recruit'],
  ['ROZ:ROZE', 'dismantle | analyse | buy up'],
  ['PŘI', 'gain weight | take on (staff) | include'],
  ['PŘE', 'take over | sort through | steal (a partner)'],
  ['PRO', 'discuss | go over | (se) come to'],
  ['DO', 'take the rest | (se) arrive at (conclusion)'],
  ['U', 'take away (some) | reduce | slow down'],
  ['ZA', 'occupy | take up | work (it worked) | (se) be absorbed'],
  ['OD:ODE', 'take away | remove | subscribe to | (se) retire'],
  ['PO', 'take (all) | (colloq.) understand'],
  ['S:SE', 'pick up | collect | steal | (se) pull oneself together'],
  ['VZ', 'take (perfective of brát)', 'Vzal si deštník. = He took an umbrella.', 'VZÍT'],
]],

['MYSLET → -MYSLET / -MÝŠLET', ['think'], [
  ['VY', 'think up | invent | make up', 'Vymyslel novou hru. = He came up with a new game.'],
  ['ROZ', '(si) think over | (si) change one’s mind'],
  ['DO', 'think through | (si) guess | infer'],
  ['PŘE', 'reflect | ponder (přemýšlet)'],
  ['PRO', 'think through | consider carefully'],
  ['ZA', '(se) reflect | (zamýšlet) intend'],
  ['OD', '(si) disregard | imagine without'],
  ['PO', 'think of | consider'],
  ['U', '(si) resolve | make up one’s mind'],
  ['S', 'think | hold views (smýšlet)'],
  ['V', '(se) put oneself in sb’s place'],
  ['NA:NÁMYSLNÝ', 'conceited | vain'],
]],

['-HLÍŽET → -HLÉDNOUT', ['look'], [
  ['O', '(se) look back | glance back', 'Ohlédl se za ní. = He looked back at her.'],
  ['VY', 'look out | pick out | (vyhlížet) look like'],
  ['NA', 'peek | look into | inspect'],
  ['PRO', 'examine | inspect | see through'],
  ['PŘE', 'overlook | miss | survey'],
  ['PŘI', 'take into account | look on'],
  ['DO', 'supervise | see as far as'],
  ['ZA', 'catch sight of | glimpse'],
  ['ROZ', '(se) look around'],
  ['OD', 'disregard | leave aside'],
  ['PO', 'look at | glance'],
  ['S:SHLÉDNOUT', 'look down | watch (a film)'],
  ['VZ', 'look up | (k) look up to'],
]],

['-PIS', [], [
  ['NAD', 'heading | title'],
  ['VY:VÝ', 'statement | extract | listing'],
  ['O', 'copy | transcript'],
  ['NA:NÁ', 'inscription | sign | notice'],
  ['ROZ', 'schedule | breakdown | itemization'],
  ['PŘI:PŘÍ', 'official letter | memo'],
  ['PŘED', 'regulation | rule | prescription'],
  ['PŘE', 'transcript | transcription'],
  ['PRO:PRŮ', 'carbon copy'],
  ['U:Ú', 'bond | pledge | debenture'],
  ['ZA:ZÁ', 'record | entry | enrolment | minutes'],
  ['OD', 'write-off | depreciation'],
  ['DO', 'letter'],
  ['PO', 'description'],
  ['S', 'file | document | written work'],
  ['POD', 'signature'],
]],

['-CHOD', [], [
  ['VY:VÝ', 'exit | way out | east | sunrise'],
  ['OB', 'shop | trade | business | deal'],
  ['ROZ', 'breakup | parting | gauge (rail)'],
  ['PŘI:PŘÍ', 'arrival | coming'],
  ['PŘE', 'crossing | transition | menopause'],
  ['PRO:PRŮ', 'passage | way through'],
  ['ZA:ZÁ', 'toilet | loo'],
  ['OD', 'departure | leaving'],
  ['DO:DŮ', 'pension | old-age benefit'],
  ['PŘED:PŘEDCHŮDCE', 'predecessor'],
  ['S', 'step | stair | (-y) stairs'],
  ['V', 'entrance | way in'],
  ['PO', 'march | procession | (chem.) process'],
  ['POD', 'underpass | subway'],
]],

['-JEZD', [], [
  ['VY:VÝ', 'exit (by car) | departure | trip abroad'],
  ['NAD', 'flyover | overpass'],
  ['NA:NÁ', 'raid | on-ramp | slip road'],
  ['OB', 'detour | diversion | roundabout'],
  ['ROZ', 'start | take-off run | launch'],
  ['PŘE', 'level crossing | transfer (by car)'],
  ['PRO:PRŮ', 'passage | drive-through'],
  ['PŘI:PŘÍ', 'arrival | access road'],
  ['DO', 'range | finish (of a race)'],
  ['ZA:ZÁ', 'package tour | excursion'],
  ['OD', 'departure'],
  ['V', 'entrance | driveway'],
  ['PO', 'undercarriage | running gear'],
  ['S', 'congress | reunion | downhill run | exit'],
  ['POD', 'underpass'],
]],

['RAZIT → -RAZIT', ['coin','mint','stamp','make one’s way'], [
  ['VY', 'set out | knock out | burst out'],
  ['NA', 'hit | bump into | come across | allude to'],
  ['ROZ', 'burst open | fling apart'],
  ['PRO', 'break through | pierce | succeed'],
  ['PŘE', 'break (in two) | snap'],
  ['PŘI', 'add (a surcharge) | push against'],
  ['ZA', 'stop | halt | drive in | (se) be taken aback'],
  ['DO', 'arrive | finish off'],
  ['U', 'insult | offend | knock off | cover (distance)'],
  ['O', 'stamp (a document)'],
  ['V', 'thrust | ram | crash into | sink (money)'],
  ['PO', 'defeat | knock down | fell | slaughter'],
  ['OD', 'repel | fend off | reflect | bounce'],
  ['S', 'knock down | cut (price) | (se) collide | curdle'],
  ['POD', 'trip up | betray | double-cross'],
]],

['-RAZ', [], [
  ['VY:VÝ', 'expression | term | look'],
  ['OB', 'picture | painting | image'],
  ['NA:NÁ', 'impact | collision | (naráz) at once'],
  ['PRO:PRŮ', 'breakthrough | puncture'],
  ['OD', 'reflection | bounce | take-off'],
  ['U:Ú', 'injury | accident'],
  ['DO:DŮ', 'emphasis | stress'],
  ['DO', 'stop | limit | (na doraz) to the max'],
  ['S', 'meeting | reunion | rendezvous'],
  ['POD', 'dirty trick | double-cross'],
]],

['-ZNAM', ['ZNAMENÍ'], [
  ['VY:VÝ', 'meaning | sense | significance'],
  ['O', 'notice | announcement (oznámení)'],
  ['ZA:ZÁ', 'record | recording | entry'],
  ['S:SE', 'list | register | index'],
  ['PO', 'note (poznámka)', null, 'POZNÁMKA'],
]],

['-STUP', [], [
  ['VY:VÝ', 'ascent | exit | output | performance | scene'],
  ['VZ:VZE', 'rise | growth | ascent'],
  ['NA:NÁ', 'boarding | onset | line-up | start'],
  ['ROZ:ROZE', 'spacing | interval'],
  ['PŘI:PŘÍ', 'access | approach | attitude'],
  ['PŘE', 'transfer | change (of trains)'],
  ['PRO:PRŮ', 'passage | penetration'],
  ['OD', 'distance | detachment | gap'],
  ['U:Ú', 'retreat | decline | concession'],
  ['ZA:ZÁ', 'crowd | host | line | (zástupce) deputy'],
  ['DO', 'dostupný = available | accessible'],
  ['V', 'entry | entrance | admission | input'],
  ['PO', 'procedure | progress | promotion'],
  ['S:SE', 'descent | relegation'],
]],

['STOUPAT → -STOUPIT', ['rise','climb','step'], [
  ['VY', 'get off | perform | appear | climb up'],
  ['OB', 'surround | gather round'],
  ['NA', 'get on | board | start (a job) | line up'],
  ['ROZ:ROZE', '(se) part | make way'],
  ['PŘI', 'approach | step up | (na) agree to'],
  ['U', 'step back | retreat | give way | recede'],
  ['PŘED', 'step forward | come before'],
  ['OD', 'resign | step down | withdraw'],
  ['PŘE', 'change (trains) | transfer | violate'],
  ['PRO', 'permeate | pervade'],
  ['ZA', 'stand in for | represent | block'],
  ['V', 'enter | join'],
  ['PO', 'advance | progress | cede'],
  ['S:SE', 'descend | come down | be relegated'],
  ['POD', 'undergo'],
]],

['-ZNAT', ['know','let be known'], [
  ['VY', 'confess | profess | (se v) know one’s way around'],
  ['PŘI', 'admit | confess | grant | (se) plead guilty'],
  ['U', 'recognize | acknowledge | accept'],
  ['ROZ:ROZE', 'distinguish | tell apart | make out'],
  ['DO', 'confess | (změn) undergo (changes)'],
  ['PO', 'get to know | meet | recognize | experience'],
]],

['RŮST → -RŮST', ['grow'], [
  ['VY', 'grow up | spring up'],
  ['VZ', 'grow | increase | rise'],
  ['OB', 'become overgrown'],
  ['NA', 'grow | increase | accumulate'],
  ['ROZ', '(se) expand | spread'],
  ['PŘI', 'grow on | (k srdci) become dear'],
  ['PŘE', 'outgrow | grow over | turn into'],
  ['PRO', 'grow through | permeate'],
  ['DO', 'grow up | reach (a size) | grow back'],
  ['ZA', 'become overgrown | grow in (nail) | heal'],
  ['OD', 'outgrow | grow out of'],
  ['V', 'grow into | take root'],
  ['PO', 'become covered (with growth)'],
  ['S', 'grow together | fuse | knit'],
]],

['BAVIT (SE) → -BAVIT', ['entertain','amuse','(se) have fun','(se) talk'], [
  ['VY', 'equip | furnish | handle | (si) recall'],
  ['OD', 'check in (passengers) | process | dispatch'],
  ['ZA', 'confiscate | seize | keep (sb) busy'],
  ['PO', 'amuse | (se) have fun | (se) chat'],
  ['Z', 'rid | free | (se) get rid of'],
]],

['-BAVA', [], [
  ['VY:VÝ', 'equipment | kit | trousseau'],
  ['ZA:ZÁ', 'fun | entertainment | party | dance'],
  ['OB', 'fear | concern | worry'],
]],

['-ZOR', [], [
  ['OB', 'horizon | outlook'],
  ['NA:NÁ', 'opinion | view'],
  ['DO', 'supervision | invigilation'],
  ['V:VZOR', 'model | pattern | example'],
  ['PO', 'attention | watch out!'],
  ['PRO:PRŮ', 'peephole | opening'],
]],

['-POMENOUT', ['[act of remembering]'], [
  ['NA', 'reprimand | admonish | warn'],
  ['PŘI', 'remind | mention | commemorate'],
  ['ROZ', '(se) recall | recollect'],
  ['U', 'send a reminder | dun'],
  ['ZA', 'forget'],
  ['VZ', '(si) remember | recall | (na) think of'],
]],

['POMÁHAT → POMOCI', ['help'], [
  ['VY', 'help out | (si) make do'],
  ['OD', 'remedy | relieve'],
  ['DO', 'help to achieve | contribute'],
]],

['ŠETŘIT → -ŠETŘIT', ['save','conserve','spare'], [
  ['VY', 'investigate | examine (medically)'],
  ['NA', 'save up | put aside'],
  ['PRO', 'look into | investigate'],
  ['U', 'save | spare | set aside'],
  ['O', 'treat | tend | dress (a wound)'],
  ['DO', 'complete (an investigation)'],
]],

['ŘEŠIT → -ŘEŠIT', ['solve','deal with'], [
  ['VY', 'solve | resolve | settle'],
  ['ROZ', 'resolve | unravel'],
  ['DO', 'finalize | sort out the rest'],
]],

['RUŠIT → -RUŠIT', ['disturb','cancel'], [
  ['VY', 'disturb | interrupt | distract'],
  ['VZ', 'excite | arouse'],
  ['ROZ', 'upset | agitate | erode'],
  ['NA', 'disrupt | breach | damage'],
  ['PŘE', 'interrupt | suspend | disconnect'],
  ['OD', 'suppress interference'],
  ['PO', 'break | breach | violate | damage'],
  ['Z', 'cancel | abolish | call off'],
]],

['-KLAD', [], [
  ['VY:VÝ', 'explanation | interpretation | lecture'],
  ['OB', 'tiling | cladding | compress'],
  ['NA:NÁ', 'load | cargo | cost | print run'],
  ['ROZ', 'decomposition | decay | breakdown'],
  ['PŘI:PŘÍ', 'example | (math) problem'],
  ['PŘE', 'translation'],
  ['DO', 'document | ID | receipt | proof'],
  ['ZA:ZÁ', 'basis | foundation | base'],
  ['U:Ú', '(úklady) plots | intrigues'],
  ['OD', 'postponement | deferral | reprieve'],
  ['V', 'deposit | contribution | stake'],
  ['PO', 'treasure | (pokladna) cash desk'],
  ['S', 'warehouse | store | composition'],
  ['POD', 'basis | background data | primer'],
]],

['-KLÁDAT', ['(imperfective)','place','lay'], [
  ['VY', 'unload | explain | tell | interpret'],
  ['OB', 'tile | clad | cover'],
  ['NA', 'load | pickle | (s) handle | treat'],
  ['ROZ', 'spread | decompose | take apart'],
  ['PŘI', 'attach | enclose | attach (importance)'],
  ['ZA', 'found | file | (si na) take pride in'],
  ['PŘE', 'translate | transfer | relocate'],
  ['PRO', 'interleave | intersperse'],
  ['DO', 'document | support with evidence'],
  ['PŘED', 'present | submit'],
  ['U', 'store | save | impose'],
  ['OD', 'postpone | put off | set aside'],
  ['V', 'insert | deposit | invest'],
  ['PO', 'consider | regard | lay'],
  ['S', 'fold | compose | take (exams)'],
  ['POD', 'underlay | back up'],
]],

['TOK', ['flow','current','stream'], [
  ['VY:VÝ', 'discharge | outflow'],
  ['PŘI:PŘÍ', 'tributary | inflow'],
  ['ZA:ZÁTOKA', 'bay | cove | inlet'],
  ['ROZ', 'solution (liquid)'],
  ['U:Ú', 'attack | offensive | (útočiště) refuge'],
  ['PRO:PRŮ', 'flow rate | throughput'],
  ['OD', 'drain | outflow | runoff'],
  ['OB', 'bypass'],
  ['PO', 'brook | stream'],
  ['S:STOKA', 'sewer'],
  ['S:SOU', 'confluence'],
]],

['-TO / -TOM', ['(in/about) it','that'], [
  ['NA', 'thereupon (nato)'],
  ['PŘI', 'at the same time | while | yet (přitom)'],
  ['PRO', 'therefore | that’s why (proto)'],
  ['PŘE:PŘES', 'nevertheless | even so (přesto)'],
  ['ZA', 'on the other hand (zato)'],
  ['PO', 'then | afterwards (potom)'],
  ['V', 'suddenly | just then (vtom)'],
]],

['-SLEDEK', ['(sled)','sequence','succession'], [
  ['VY:VÝ', 'result | outcome'],
  ['NA:NÁ', 'consequence | aftermath'],
  ['DO:DŮ', 'consequence | implication'],
  ['PO', '(naposledy) last time | (posléze) later'],
]],

['ZNAK', ['sign','character','feature','emblem','backstroke'], [
  ['NA:NÁ', 'hint | trace | suggestion'],
  ['PŘI:PŘÍ', 'symptom | sign'],
  ['OD', 'badge | pin'],
]],

['KLONIT / KLANĚT SE → -KLONIT', ['incline','bend','tip','(se) bow'], [
  ['VY', '(se) lean out'],
  ['OD', 'divert | deflect | (se) deviate'],
  ['PŘI', '(se k) lean towards | side with'],
  ['NA', 'tilt | incline | (si) win over'],
  ['U', '(se) bow'],
  ['ZA', 'lean back | tilt back'],
  ['PŘED', '(se) bend forward'],
  ['PO', '(se) bow (to) | pay homage'],
  ['S', 'lower | bow | (se) stoop | bend down'],
]],

['STÍHAT → -STIHNOUT', ['manage (in time)','catch','prosecute'], [
  ['VY', 'capture | express aptly | hit the nail'],
  ['PŘI', 'catch in the act'],
  ['PŘED', 'outstrip | get ahead of'],
  ['ZA', 'catch | find (sb at home)'],
  ['DO', 'catch up with | overtake'],
  ['PO', 'afflict | strike | penalize'],
]],

['HRÁT → -HRÁT', ['HRÁVAT','play'], [
  ['VY', 'win', 'Vyhráli zápas. = They won the match.'],
  ['NA', 'record | pass (ball) | play into sb’s hands'],
  ['PŘE', 'play (back) | replay | outplay'],
  ['PRO', 'lose', 'Prohráli dva nula. = They lost two–nil.'],
  ['ROZ:ROZE', 'open (a game) | (se) warm up'],
  ['ZA', 'play (perfective) | (si) have a game'],
  ['PŘI', 'pass (ball)'],
  ['U', 'secure (a result)'],
  ['DO', 'finish playing'],
  ['OD:ODE', 'play (a match) | (se) take place'],
  ['PO', '(si) play with | toy with | tinker'],
  ['S:SE', 'perform | play (a role) | (se) gel (as a team)'],
]],

['ROK', ['year','(archaic) speech, fate'], [
  ['VY:VÝ', 'statement | verdict | pronouncement'],
  ['OB', 'feed (oats) | fodder'],
  ['NA:NÁ', 'claim | entitlement | (nároky) demands'],
  ['U:Ú', 'interest (on money)'],
  ['PRO', 'prophet'],
]],

['ROD', ['family','lineage','clan','genus','gender'], [
  ['NA:NÁROD', 'nation | people'],
  ['OB', 'revival | renewal (obroda)'],
  ['PŘI:PŘÍRODA', 'nature'],
  ['PŘE', 'transformation | rebirth (přerod)'],
  ['U:ÚRODA', 'harvest | crop | yield'],
  ['ZA:ZÁRODEK', 'embryo | germ | seed'],
  ['OD', 'variety | breed (odroda)'],
  ['PO', 'childbirth | delivery (porod)'],
  ['V', 'innate | inborn (vrozený)'],
  ['Z', 'birth | genesis (zrod)'],
  ['POD', 'subgenus'],
]],

/* ---------- cards with example sentences ---------- */

['PÍT → -PÍT', ['drink'], [
  ['VY', 'drink up', 'Vypil celou láhev vína. = He drank the whole bottle of wine.'],
  ['DO', 'finish drinking', 'Dopij tu kávu, jdeme. = Finish your coffee, we’re going.'],
  ['NA', '(se) have a drink', 'Napij se vody. = Have a drink of water.'],
  ['PŘE', 'outdrink | (se) drink too much', 'Nikdo ho nepřepije. = Nobody can outdrink him.'],
  ['PRO', 'spend on drink', 'Propil celou výplatu. = He drank away his whole paycheck.'],
  ['ZA', 'wash down | toast (a success)', 'Zapil prášek vodou. = He washed the pill down with water.'],
  ['PO', 'have a few drinks | drink a little', 'Večer jsme spolu trochu popili. = We had a few drinks together in the evening.'],
  ['O', 'get sb drunk | (se) get drunk', 'Na svatbě se opil. = He got drunk at the wedding.'],
  ['OD', 'take a sip', 'Odpila si z hrnku. = She took a sip from the mug.'],
  ['U', '(se) drink oneself to death', 'Upil se k smrti. = He drank himself to death.'],
  ['S', '(se) get drunk', 'Spil se do němoty. = He drank himself senseless.'],
]],

['SPÁT → -SPAT', ['SPÁVAT','sleep'], [
  ['VY', '(se) get a good sleep | (se s) sleep with', 'Konečně jsem se vyspal. = I finally got a good night’s sleep.'],
  ['ZA', 'oversleep', 'Zaspal a přišel pozdě. = He overslept and came late.'],
  ['PŘE', 'stay the night | sleep on (a decision)', 'Můžu u vás přespat? = Can I stay the night at your place?'],
  ['PRO', 'sleep through', 'Prospal celý film. = He slept through the whole film.'],
  ['DO', 'catch up on sleep', 'O víkendu to dospím. = I’ll catch up on sleep at the weekend.'],
  ['NA', 'get (enough) sleep', 'Mám málo naspáno. = I haven’t had much sleep.'],
  ['PO', '(si) take a nap', 'Po obědě si pospal. = He had a nap after lunch.'],
  ['U', 'put to sleep | anaesthetize', 'Uspala dítě písničkou. = She sang the baby to sleep.'],
]],

['STÁT → -STÁT / -STAT', ['STÁVAT','stand','cost','(se) become'], [
  ['PO', 'stand for a while', 'Chvíli postál u okna. = He stood at the window for a while.'],
  ['ZA', '(se) stand up for | do (a job)', 'Vždycky se mě zastane. = He always stands up for me.'],
  ['PŘE', 'stop | cease', 'Přestalo pršet. = It stopped raining.'],
  ['OD', 'settle | stand (to settle)', 'Nech vodu odstát. = Let the water stand.'],
  ['VY', 'stand | endure (usually negated)', 'Nemůžu ho vystát. = I can’t stand him.'],
  ['NA', 'set in | occur | come', 'Nastalo ticho. = Silence fell.'],
  ['OB', 'hold up | pass (a test)', 'U zkoušky obstál. = He passed the exam.'],
  ['V', 'get up | stand up', 'Vstal brzy ráno. = He got up early in the morning.'],
  ['DO', 'live up to | keep (a promise)', 'Dostál svému slibu. = He kept his promise.'],
  ['U', 'withstand | cope with', 'Ten tlak ustál. = He withstood the pressure.'],
  ['Z:ZŮSTAT', 'stay | remain', 'Zůstal doma. = He stayed at home.', 'ZŮSTAT'],
]],

['SEDĚT / -SEDAT → -SEDNOUT', ['SEDÁVAT','sit'], [
  ['PŘI', '(si) sit down next to | join', 'Přisedl si k nám. = He sat down with us.'],
  ['VY', 'hatch | sit out', 'Slepice vyseděla kuřata. = The hen hatched her chicks.'],
  ['PŘE', 'change seats | change (to)', 'Přesedl do vlaku. = He changed to the train.'],
  ['ZA', 'take one’s seat | convene', 'Zasedli ke stolu. = They sat down at the table.'],
  ['PO', 'sit a while (posedět)', 'Posedíme u kávy. = We’ll sit and have a coffee.', 'POSEDĚT'],
  ['OB:OBSADIT', 'occupy | cast (roles) | fill (a post)', 'Obsadili město. = They occupied the city.', 'OBSADIT'],
  ['NA', 'get on | mount', 'Nasedl na kolo. = He got on his bike.'],
  ['S:SE', 'get off | dismount', 'Sesedl z koně. = He dismounted from the horse.'],
  ['U', 'sit down | settle', 'Usedl do křesla. = He sat down in the armchair.'],
  ['OD', '(si) serve (a sentence)', 'Odseděl si pět let. = He served five years.', 'ODSEDĚT'],
  ['PRO', 'spend (time) sitting', 'Proseděl celý den u počítače. = He spent the whole day sitting at the computer.', 'PROSEDĚT'],
]],

['VÉST → -VÉST', ['VODÍVAT','lead','conduct'], [
  ['OD', 'take away | pay (tax) | do (a job)', 'Odvedl dobrou práci. = He did a good job.'],
  ['PŘI', 'bring (sb) | lead to', 'Přivedl na večírek kamaráda. = He brought a friend to the party.'],
  ['DO', 'lead (to) | be able to', 'Dovedl nás až k řece. = He led us all the way to the river.'],
  ['PŘE', 'transfer | convert | lead across', 'Převedl peníze na účet. = He transferred the money to the account.'],
  ['PRO', 'carry out | show round', 'Provedli nás po zámku. = They showed us round the chateau.'],
  ['VY', 'lead out | export | (z míry) disconcert', 'Vyvedl psa na procházku. = He took the dog out for a walk.'],
  ['ZA', 'introduce | take (sb to)', 'Zavedli nový systém. = They introduced a new system.'],
  ['NA', 'guide | direct | incite', 'Navedl pilota na přistání. = He guided the pilot in to land.'],
  ['U', 'state | introduce | put into (operation)', 'Uveďte své jméno. = State your name.'],
  ['S', 'seduce | lead astray | manage', 'Svedla ho. = She seduced him.'],
  ['ROZ', '(se) divorce | elaborate', 'Loni se rozvedli. = They got divorced last year.'],
  ['PO', '(se) turn out well | succeed', 'Dort se povedl. = The cake turned out well.'],
  ['PŘED', 'demonstrate | show', 'Předvedl nový výrobek. = He demonstrated the new product.'],
  ['OB', 'trace around | enclose', 'Obvedl ruku tužkou. = He traced around his hand with a pencil.'],
  ['POD', 'cheat | deceive | cheat on', 'Podvedl manželku. = He cheated on his wife.'],
]],

['NÉST / -NÁŠET → -NÉST', ['NOSÍVAT','carry','bear'], [
  ['PŘI', 'bring', 'Přinesl květiny. = He brought flowers.'],
  ['OD', 'carry away | take away', 'Odnesl židli do kuchyně. = He carried the chair to the kitchen.'],
  ['DO', 'bring | fetch | tell on (sb)', 'Doneseš mi noviny? = Will you bring me the newspaper?'],
  ['PŘE', 'carry over | transmit | broadcast', 'Přenesl krabice do auta. = He carried the boxes over to the car.'],
  ['PRO', 'deliver (a speech) | smuggle', 'Pronesl krátký projev. = He gave a short speech.'],
  ['VY', 'carry out | yield | pronounce (verdict)', 'Vynes koš. = Take out the rubbish.'],
  ['ZA', 'take (to) | clog up | enter (in records)', 'Zanesl dopis na poštu. = He took the letter to the post office.'],
  ['PO', 'carry | bear (consequences)', 'Ponese následky. = He will bear the consequences.'],
  ['NA', 'apply (a coat)', 'Nanesl barvu na zeď. = He applied paint to the wall.'],
  ['S', 'tolerate | bring down | lay (an egg)', 'Nesnese kritiku. = He can’t stand criticism.'],
  ['U', 'kidnap | hijack | manage to carry', 'Unesli letadlo. = They hijacked the plane.'],
  ['ROZ', 'deliver (around) | spread', 'Roznesl letáky. = He delivered the leaflets.'],
  ['PŘED', 'recite | deliver (a lecture)', 'Přednesla báseň. = She recited a poem.'],
  ['VZ', 'raise (an objection) | (se) soar', 'Vznesl námitku. = He raised an objection.'],
  ['NAD', 'raise (a topic) | lift', 'Nadnesl zajímavou otázku. = He raised an interesting question.'],
]],

['VOZIT / -VÁŽET → -VÉZT', ['VOZÍVAT','transport','drive'], [
  ['PŘI', 'bring (by vehicle)', 'Přivezl dárky z Itálie. = He brought gifts back from Italy.'],
  ['OD', 'drive away | take (by vehicle)', 'Odvezu tě domů. = I’ll drive you home.'],
  ['DO', 'import | deliver', 'Dovezli zboží z Číny. = They imported goods from China.'],
  ['PŘE', 'transport | transfer | (colloq.) con', 'Převezli pacienta do nemocnice. = They took the patient to hospital.'],
  ['VY', 'export | take out', 'Vyvezli odpad za město. = They took the waste out of town.'],
  ['NA', 'bring in (loads)', 'Navezli hlínu na zahradu. = They brought soil into the garden.'],
  ['ZA', 'drive (sb to) | fill in (a pit)', 'Zavezl mě na nádraží. = He drove me to the station.'],
  ['ROZ', 'deliver (around)', 'Rozvezl pizzy. = He delivered the pizzas.'],
  ['S', 'give a lift | (se) get a ride', 'Svezeš mě? = Will you give me a lift?'],
  ['PRO', 'drive (sb) around', 'Provezl nás po městě. = He drove us around the town.'],
]],

['LETĚT / -LÉTAT → -LETĚT', ['LÉTÁVAT','fly'], [
  ['OD', 'fly away | depart', 'Letadlo odletělo včas. = The plane left on time.'],
  ['PŘI', 'arrive (by air) | fly in', 'Přiletěl z Londýna. = He flew in from London.'],
  ['PŘE', 'fly over | fly across', 'Přeletěli oceán. = They flew across the ocean.'],
  ['PRO', 'fly through | (colloq.) flunk', 'Proletěl u zkoušky. = He flunked the exam.'],
  ['VY', 'fly out | shoot up | fly off the handle', 'Ceny vyletěly nahoru. = Prices shot up.'],
  ['DO', 'reach (by flying)', 'Doletěli až do Prahy. = They flew as far as Prague.'],
  ['ZA', 'fly (in, off to)', 'Pták zaletěl do pokoje. = A bird flew into the room.'],
  ['VZ:VZLÉTNOUT', 'take off', 'Letadlo vzlétlo. = The plane took off.', 'VZLÉTNOUT'],
  ['U', 'fly off | (colloq.) miss (a bus)', 'Uletěl mi autobus. = I just missed the bus.'],
  ['ROZ', '(se) fly open | scatter', 'Dveře se rozletěly. = The door flew open.'],
  ['S:SLÉTNOUT', 'swoop down | (se) flock together', 'Holubi slétli na náměstí. = The pigeons flew down onto the square.', 'SLÉTNOUT'],
  ['NA', 'fall for (a trick)', 'Naletěl podvodníkovi. = He fell for the con man.'],
]],

['TÉCT / -TÉKAT → -TÉCT', ['flow','run','leak'], [
  ['OD', 'flow away | drain', 'Voda odtekla. = The water drained away.'],
  ['PŘI', 'flow in', 'Do nádrže přiteklo hodně vody. = A lot of water flowed into the reservoir.'],
  ['PŘE', 'overflow', 'Vana přetekla. = The bath overflowed.'],
  ['PRO', 'flow through | leak through', 'Střechou proteklo. = Water leaked through the roof.'],
  ['VY', 'flow out | leak out', 'Z krabice vyteklo mléko. = Milk leaked out of the carton.'],
  ['NA', 'swell up | leak in', 'Kotník mi natekl. = My ankle swelled up.'],
  ['ZA', 'seep in', 'Do sklepa zateklo. = Water got into the cellar.'],
  ['U', 'run away | escape | (time) fly', 'Pes utekl. = The dog ran away.'],
  ['S', 'trickle down | run down', 'Slza jí stekla po tváři. = A tear ran down her cheek.'],
  ['ROZ:ROZU', '(se) scatter | run off', 'Děti se rozutekly. = The children scattered.'],
]],

['PADAT → -PADNOUT', ['PADÁVAT','fall'], [
  ['VY', 'look (vypadat) | fall out | get out! (colloq.)', 'Vypadá unaveně. = He looks tired.', 'VYPADAT'],
  ['ZA', 'set (sun) | fit in | get stuck', 'Slunce zapadlo. = The sun set.'],
  ['PŘE', 'attack | mug | ambush', 'V parku ho přepadli. = He was mugged in the park.'],
  ['PRO', 'fail | expire | fall through', 'Propadl z matematiky. = He failed maths.'],
  ['OD', 'be cancelled | fall off | drop out', 'Hodina odpadla. = The lesson was cancelled.'],
  ['NA', 'occur to | attack | (snow) fall', 'Napadlo mě to. = It occurred to me.'],
  ['DO', 'turn out | land | catch (a culprit)', 'Jak to dopadlo? = How did it turn out?'],
  ['PŘI', 'seem (připadat) | fall to (sb)', 'Připadá mi to divné. = It seems strange to me.', 'PŘIPADAT'],
  ['U', 'fall down | lapse into', 'Upadl na ledu. = He fell on the ice.'],
  ['ROZ', '(se) fall apart | break up', 'Kapela se rozpadla. = The band broke up.'],
  ['S', 'fall (down)', 'Spadl ze stromu. = He fell out of the tree.'],
  ['PO', 'grab | seize', 'Popadl kabát a odešel. = He grabbed his coat and left.'],
  ['V', 'burst in | invade', 'Vpadl do místnosti. = He burst into the room.'],
]],

['MLUVIT / -MLOUVAT → -MLUVIT', ['MLUVÍVAT','speak','talk'], [
  ['DO', 'arrange | finish speaking | (se) communicate', 'Domluvili jsme si schůzku. = We arranged a meeting.'],
  ['PŘE', 'persuade | talk into', 'Přemluvil mě, abych šel. = He talked me into going.'],
  ['OD', 'talk back (odmlouvat)', 'Neodmlouvej! = Don’t talk back!', 'ODMLOUVAT'],
  ['PO', 'slander | badmouth', 'Pomluvila ji u šéfa. = She badmouthed her to the boss.'],
  ['NA', 'make sb believe | record (voice)', 'Namluvil mi, že je doktor. = He made me believe he was a doctor.'],
  ['VY', '(se) make excuses | talk out of', 'Vymluvil se na nemoc. = He used illness as an excuse.'],
  ['ZA', 'book | reserve | (se za) put in a word', 'Zamluvil stůl na osmou. = He booked a table for eight.'],
  ['PŘI', '(se) intercede | put in a word', 'Přimluvil se za mě. = He put in a good word for me.'],
  ['PRO', 'speak (up) | talk to', 'Musím s tebou promluvit. = I need to talk to you.'],
  ['S', 'agree on | arrange (smlouva = contract)', 'Smluvili si cenu. = They agreed on a price.'],
  ['ROZ', 'talk sb out of', 'Rozmluvila mu ten nápad. = She talked him out of the idea.'],
  ['U', 'talk into | (se) agree', 'Nechal se umluvit. = He let himself be talked into it.'],
]],

['UČIT (SE) → -UČIT', ['UČÍVAT','teach','(se) learn'], [
  ['NA', 'teach | (se) learn', 'Naučil se česky. = He learned Czech.'],
  ['VY', '(se) qualify in a trade | teach', 'Vyučil se truhlářem. = He trained as a carpenter.'],
  ['DO', 'tutor | finish teaching', 'Doučuje matematiku. = He tutors maths.'],
  ['PŘE', 'retrain | (se) relearn', 'Musel se přeučit na nový systém. = He had to retrain for the new system.'],
  ['OD:ODNA', 'break sb of | (se) unlearn', 'Odnaučil se kouřit. = He broke the habit of smoking.'],
  ['PO', 'instruct | inform | (se) learn from', 'Poučil se z chyb. = He learned from his mistakes.'],
  ['ZA', 'train (a newcomer) | break in', 'Zaučila nového kolegu. = She trained the new colleague.'],
]],

['PLATIT / -PLÁCET → -PLATIT', ['PLATÍVAT','pay','be valid'], [
  ['ZA', 'pay (perfective)', 'Zaplatil účet. = He paid the bill.'],
  ['DO', 'pay dearly (for) | pay the rest', 'Doplatil na svou lehkomyslnost. = He paid dearly for his carelessness.'],
  ['VY', '(se) be worth it | pay out', 'Vyplatilo se to. = It was worth it.'],
  ['PŘE', 'overpay', 'Přeplatil zálohy na energie. = He overpaid on his energy bills.'],
  ['PRO', 'reimburse | cash', 'Firma mu proplatila cestu. = The company reimbursed his travel.'],
  ['O', 'repay | return (a favour)', 'Oplatil mu to. = He paid him back for it.'],
  ['OD:ODPLATA', 'retribution | reward', null, 'ODPLATA'],
  ['S', 'pay off | repay', 'Splatil hypotéku. = He paid off the mortgage.'],
  ['PŘED', 'subscribe (to) | prepay', 'Předplatil si noviny. = He subscribed to the newspaper.'],
  ['PŘI', 'pay extra', 'Připlatil si za výhled. = He paid extra for the view.'],
  ['U', 'bribe', 'Uplatil úředníka. = He bribed the official.'],
]],

['VAŘIT → -VAŘIT', ['VAŘÍVAT','cook','boil'], [
  ['U', 'cook | make (tea, coffee)', 'Uvařila večeři. = She cooked dinner.'],
  ['PŘE', 'boil (to sterilize)', 'Převař vodu. = Boil the water.'],
  ['DO', 'finish cooking', 'Dovařím a jdu. = I’ll finish cooking and then go.'],
  ['ZA', 'preserve (in jars) | (colloq.) cause trouble', 'Babička zavařila meruňky. = Grandma preserved some apricots.'],
  ['VY', 'boil (clean) | boil down', 'Vyvařila prádlo. = She boiled the laundry.'],
  ['NA', 'cook a lot', 'Navařila na celý týden. = She cooked for the whole week.'],
  ['PRO', '(colloq.) blow sb’s cover'],
  ['S', 'weld', 'Svařil trubky. = He welded the pipes.'],
  ['ROZ', 'overcook (to mush)', 'Rozvařil těstoviny. = He overcooked the pasta.'],
  ['PŘI', 'weld on'],
]],

['STAVĚT → -STAVIT', ['build','put','stop'], [
  ['PO', 'build | stand (sth) up', 'Postavili nový most. = They built a new bridge.'],
  ['PŘE', 'rebuild | convert (přestavět)', 'Přestavěli starou továrnu. = They converted the old factory.', 'PŘESTAVĚT'],
  ['ZA', 'stop | pawn', 'Zastavil auto. = He stopped the car.'],
  ['DO', 'finish building (dostavět)', 'Dům dostavěli loni. = They finished building the house last year.', 'DOSTAVĚT'],
  ['VY', 'issue | exhibit | expose', 'Vystavil fakturu. = He issued an invoice.'],
  ['OD', 'park | set aside | wean', 'Odstavil auto na parkovišti. = He left the car in the car park.'],
  ['NA', 'set | adjust | extend', 'Nastav budík na šest. = Set the alarm for six.'],
  ['PŘED', 'introduce | (si) imagine', 'Představil mi svou ženu. = He introduced his wife to me.'],
  ['PŘI', 'bring round (a vehicle)', 'Přistavili autobus. = They brought the bus round.'],
  ['S:SE', 'put together | compile | assemble', 'Sestavil tým. = He put together a team.'],
  ['U', 'establish | set up', 'Ustavili komisi. = They set up a commission.'],
  ['ROZ:ROZE', 'arrange | set out', 'Rozestavil figurky na šachovnici. = He set out the pieces on the chessboard.'],
]],

['MĚŘIT → -MĚŘIT', ['measure'], [
  ['OD', 'measure out | (odměřený) aloof', 'Odměř sto gramů mouky. = Measure out a hundred grams of flour.'],
  ['NA', 'measure | record (a reading)', 'Naměřili třicet stupňů. = They recorded thirty degrees.'],
  ['PŘE', 're-measure', 'Přeměř to ještě jednou. = Measure it again.'],
  ['VY', 'survey | assess (tax) | impose', 'Vyměřili mu daň. = They assessed his tax.'],
  ['ZA', '(se) focus on | aim | survey', 'Zaměřil se na ekonomii. = He focused on economics.'],
  ['Z', 'measure (perfective)', 'Změřil místnost. = He measured the room.'],
  ['PO', 'measure against | compare', 'Poměřili síly. = They measured their strength against each other.'],
]],

['TVOŘIT → -TVOŘIT', ['create','form'], [
  ['VY', 'create | form', 'Vytvořil nový web. = He created a new website.'],
  ['S', 'create (bring into being)', 'Bůh stvořil svět. = God created the world.'],
  ['PŘE', 'transform | remodel', 'Přetvořil starou stodolu na ateliér. = He turned an old barn into a studio.'],
  ['DO', 'complete | round off', 'Hudba dotvořila atmosféru. = The music completed the atmosphere.'],
  ['U', 'form', 'Utvořte skupiny. = Form groups.'],
]],

['MĚNIT → -MĚNIT', ['change'], [
  ['VY', 'exchange | replace | swap', 'Vyměnil žárovku. = He replaced the light bulb.'],
  ['ZA', 'mistake (for) | confuse', 'Zaměnil ho za bratra. = He mistook him for his brother.'],
  ['PŘE', 'transform | convert', 'Přeměnili sklad na byt. = They converted the warehouse into a flat.'],
  ['OD', 'reward', 'Odměnil ho za pomoc. = He rewarded him for his help.'],
  ['PRO', 'convert | transform', 'Proměnil penaltu. = He converted the penalty.'],
  ['S', 'exchange (money)', 'Směnil eura na koruny. = He changed euros into crowns.'],
  ['Z', 'change (perfective)', 'Změnil názor. = He changed his mind.'],
  ['ROZ', 'break (a banknote)', 'Můžete mi rozměnit stovku? = Can you break a hundred for me?'],
]],

['PLNIT → -PLNIT', ['fill','fulfil'], [
  ['NA', 'fill', 'Naplnil sklenici vodou. = He filled the glass with water.'],
  ['DO', 'fill in (gaps) | top up | add', 'Doplnil chybějící údaje. = He filled in the missing details.'],
  ['VY', 'fill in (a form)', 'Vyplnil formulář. = He filled in the form.'],
  ['S', 'fulfil | meet (a condition)', 'Splnil slib. = He kept his promise.'],
  ['PŘE', 'overfill | overcrowd', 'Autobus byl přeplněný. = The bus was overcrowded.'],
  ['ZA', 'fill up (a space)', 'Diváci zaplnili stadion. = Spectators filled the stadium.'],
]],

['KONČIT → -KONČIT', ['end','finish'], [
  ['S', 'finish | end', 'Skončil práci v pět. = He finished work at five.'],
  ['DO', 'complete', 'Dokončil projekt včas. = He completed the project on time.'],
  ['U', 'end | terminate', 'Ukončil hovor. = He ended the call.'],
  ['ZA', 'round off | conclude', 'Zakončil proslov vtipem. = He rounded off the speech with a joke.'],
]],

];

/* Expand the compact rows into the shape the page draws from. */
const VERBS = RAW.map(([title, base, rows], i) => ({
  id: i + 1,
  title,
  base,
  lemmas: title.split(/[→\/:]/).map(s => s.trim()).filter(Boolean),
  entries: rows.map(([spec, glosses, ex, words]) => {
    const [slot, label] = spec.split(':');
    const e = { slot, label: label || slot, glosses: glosses ? glosses.split(' | ') : [] };
    if (ex) { const [cs, en] = ex.split(' = '); e.ex = [{ cs, en }]; }
    if (words) e.words = words.split(' ');
    return e;
  })
}));
